AWSTemplateFormatVersion: "2010-09-09"
Description: Template to build lambdas and dependencies for lambdas

Parameters:

  ProcessTradeDataK:
    Type: String
    Description: The key of ProcessTradeData lambda
  EarningAtRiskK:
    Type: String
    Description: The key of EarningAtRisk lambda
  CheckEARSummaryOutputK:
    Type: String
    Description: The key of CheckEARSummaryOutput lambda
  GetPercentileK:
    Type: String
    Description: The key of GetPercentileOutputs lambda
  EARHHTracesK:
    Type: String
    Description: The key of EARHHTraces lambda
  SendOutputsK:
    Type: String
    Description: The key of SendOutputs lambda
  CreateBucketNBEK:
    Type: String
    Description: The key of CreateBucketNBE lambda
  SimulateHistoryK:
    Type: String
    Description: The key of SimulateHistory lambda
  SimulateCustomerDataK:
    Type: String
    Description: The key of SimulateCustomerData lambda
  BucketName:
    Type: String
    Description: Name of the bucket
  Name:
    Type: String
    Description: Name of the stack

Resources:
  LambdaRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: LambdaRequired
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: LambdaPolicy
                Action:
                  - 's3:*'
                  - 'sns:*'
                  - 'ec2:*'
                  - 'lambda:*'
                Effect: Allow
                Resource: '*'
              - Sid: CloudWatchWriteLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'


  ProcessTradeDataLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref ProcessTradeDataK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-process-trade-data
      MemorySize: 700
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 900
      Layers:
        - arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python36-SciPy1x:35
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:pandas_pytz:1
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:xlrd:9
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}
          EarningAtRiskFunc:
            Fn::Sub: ${AWS::StackName}-earning-at-risk
          CheckEARSummaryOutputFunc:
            Fn::Sub: ${AWS::StackName}-check-ear-summary-output

  EarningAtRiskLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref EarningAtRiskK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-earning-at-risk
      MemorySize: 700
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 900
      Layers:
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:pyarrow-s3fs-pandas:3
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}

  CheckEARSummaryOutputLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref CheckEARSummaryOutputK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-check-ear-summary-output
      MemorySize: 128
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 120
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}
          GetPercentileOutputsFunc:
            Fn::Sub: ${AWS::StackName}-get-percentile-outputs

  GetPercentileOutputsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref GetPercentileK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-get-percentile-outputs
      MemorySize: 1024
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Layers:
        - arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python36-SciPy1x:35
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:pandas-py36:1
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:fsspec:1
      Timeout: 900
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}

  EARHHTracesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref EARHHTracesK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-ear-hh-traces
      MemorySize: 2048
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Layers:
        - arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python36-SciPy1x:35
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:pandas-py36:1
      Timeout: 900
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}
          SendOutputsFunc:
            Fn::Sub: ${AWS::StackName}-send-outputs-via-email

  SendOutputsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref SendOutputsK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-send-outputs-via-email
      MemorySize: 128
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Timeout: 900
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}

  CreateBucketNBELambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref CreateBucketNBEK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-create-bucket
      Handler: "create_bucket.handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}
      Timeout: 900

  SimulateHistoryLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref SimulateHistoryK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-simulate-history
      MemorySize: 1024
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Layers:
        - arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python36-SciPy1x:35
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:pandas-py36:1
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:xlrd:9
      Timeout: 900
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}

  SimulateCustomerDataLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': 'NBEEarningAtRiskArtifactsBucket'
        S3Key: !Ref SimulateCustomerDataK
      FunctionName:
        Fn::Sub: ${AWS::StackName}-simulate-customer-data
      MemorySize: 1024
      Handler: "lambda_function.lambda_handler"
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: python3.6
      Layers:
        - arn:aws:lambda:ap-southeast-2:817496625479:layer:AWSLambda-Python36-SciPy1x:35
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:pandas-py36:1
        - arn:aws:lambda:ap-southeast-2:000581985601:layer:xlrd:9
      Environment:
        Variables:
          StackName: !Ref AWS::StackName
          BucketName:
            Fn::Sub: ${BucketName}${Name}
      Timeout: 900


  PermissionForEventsToInvokeProcessTradeDataLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessTradeDataLambda
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}${Name}"

  PermissionForEventsToInvokeEarningAtRiskLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EarningAtRiskLambda
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt [ProcessTradeDataLambda, Arn]

  PermissionForEventsToInvokeCheckEARSummaryOutputLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CheckEARSummaryOutputLambda
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt [ProcessTradeDataLambda, Arn]

  PermissionForEventsToInvokeGetPercentileOutputsLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref GetPercentileOutputsLambda
      Principal: sns.amazonaws.com
      SourceArn: !GetAtt [CheckEARSummaryOutputLambda, Arn]

  PermissionForEventsToInvokeEARHHTracesLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref EARHHTracesLambda
      Principal: sns.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}${Name}"

  PermissionForEventsToInvokeSendOutputsLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref SendOutputsLambda
      Principal: lambda.amazonaws.com
      SourceArn: !GetAtt [EARHHTracesLambda, Arn]

  PermissionForEventsToInvokeSimulateHistoryLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SimulateHistoryLambda
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}${Name}"

  PermissionForEventsToInvokeSimulateCustomerDataLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SimulateCustomerDataLambda
      Action: "lambda:InvokeFunction"
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${BucketName}${Name}"
