version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r NBE_get_percentile_outputs/requirements.txt -t NBE_get_percentile_outputs

artifacts:
  base-directory: NBE_get_percentile_outputs
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
