version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install -r NBE_send_outputs_via_emails/requirements.txt -t NBE_send_outputs_via_emails

artifacts:
  base-directory: NBE_send_outputs_via_emails
  files:
    - '**/*'
  type: zip

cache:
  paths:
    - /root/.cache/pip
